### ISSUE TITLE
Possible to send Toast to another Win 10 box on the network?

### ISSUE THREAD

**Issue by wazooda** [Windos/BurntToast#33]
I have an need to send a toast to another Win 10 box on my LAN after a home automation event is triggered on my automation rig.

I could run BurntToast on the remote boxes, but not sure if that matters.

I'm not a programmer... but a tinkerer... so was able to get your app running fine and triggered correctly on my local box. Just hoping it will do that extra bit.

Thanks!

**Comment by fruza** [comment]
And using the HTTP Listener??: https://github.com/Windos/BurntToast/tree/master/Examples/Example08

Regards!.

**Comment by brendantop** [comment]
The Invoke-Command method partially works. Text is fine but any images referenced wether logo, hero or inline all fail to load. Each image registers an "Access is denied" followed by a "Cannot find path X because it does not exist.". Paths definitely exist, permissions don't seem to be an issue and every machine can successfully find the images if the code is run locally. The images are referenced via a UNC path and I am using version 0.7.0. Any suggestions?

**Comment by Windos** [comment]
I imagine it's the same issue as you'd run into if running a scheduled task with "Do not store password" ticked, which only gives access to local resources (i.e. anything on a UNC path would not be accessible.)

Not sure of a workaround atm, I still need to come up with the 100% fail proof method of running these remotely.

**Comment by Windos** [comment]
In addition to previous comments about scheduled tasks, you can also get around having to have BurntToast installed on the remote machine. See: https://toastit.dev/2018/08/21/crouton-8-i-like-your-code-but-i-dont-want-it-on-all-my-computers/

Also, if you do go the scheduled task route, you can execute as system and kick the toast over to the user. See: https://github.com/Windos/BurntToast/issues/27#issuecomment-666203518
