### ISSUE TITLE
New-BTText with style adds characters to the content

### ISSUE THREAD

**Issue by Robert-LTH** [Windos/BurntToast#52]
Hello,

If you run the following code you end up with an initial { before the text you specify:
New-BTText -Text 'My Text' -Style Title

Which style i use does not seem to matter but i didnt try them all.

I am using:
Windows 10 1803 with latest CU
WindowsPowershell 5.1
BurntToast 0.6.2

**Comment by Windos** [comment]
Hmm, after an update of the UWP toolkit a long time ago it started adding curly braces to text, and I had to add some code to strip them out. However, looks like specifying a style adds more braces than I was expecting...

I'll look at a fix, I also need to check to see that these styles have actually been implemented correctly, as they don't appear to have any effect on the style of the text.

Given they don't seems to have much effect anyway, other than adding that stray brace, workaround for now is to not specific a style at all.

**Comment by Windos** [comment]
It's amazing what 20/20 hindsight will get you. Those curly braces were coming from "bindable" strings which is the backbone for updating toasts.

I'm now properly supporting this bindable text (rather than just brute-forcing the curly braces away), and styles are no longer resulting in what you were seeing.

This is all wrapped up in the next release (0.7.0), so keep an eye out for that!

n.b. Styles still don't seem to *do* anything, but I've left them in so as to not break things is people have specified them.

**Comment by Syrah-NL** [comment]
I'm still getting curly brackets around my title and my text, even with the simplest notification.

`New-BurntToastNotification -SuppressPopup -UniqueIdentifier 'skyline' -AppLogo D:\XAMPP\htdocs\root\skyline\favicon.ico -Text 'Skyline Notifier', '%retVar%'`
