### ISSUE TITLE
Win 10-1809 - Toasts not working. 

### ISSUE THREAD

**Issue by Tuxhedoh** [Windos/BurntToast#61]
When I run new-burnttoastnotification -text "My text here"
My notification looks like this 
![image](https://user-images.githubusercontent.com/24434458/53265369-1a98b100-36ac-11e9-875b-7efc1b23871b.png)

**Comment by Windos** [comment]
Hey there, what version of BurntToast are you running, and any changes made
to the config.json file?

**Comment by Tuxhedoh** [comment]
BT Version Using 0.6.3 - I don't think I've made any changes to the config. I installed it a while ago, but just came back to playing.

**Comment by Windos** [comment]
Can I get you to run `new-burnttoastnotification -text "My text here" -whatif` and paste the output here?

**Comment by Tuxhedoh** [comment]
`What if: Performing the operation "New-BurntToastNotification" on target "submitting: [ToastContent] with AppId @{AppId={1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\WindowsPowerShell\v1.0\powershell.exe; AppLogo=\Images\BurntToast.png}.AppId and XML: <?xml version="1.0" encoding="utf-8"?><toast><visual><binding template="ToastGeneric"><text>{Server Update}</text><image src="{local serverdir}\My Documents\WindowsPowerShell\Modules\BurntToast\0.6.3\Images\BurntToast.png" placement="appLogoOverride" hint-crop="circle" /></binding></visual></toast>".`

**Comment by Windos** [comment]
Thanks for that, running that XML directly, I get the same result (this is the default toast you see when the XML is invalid.)

In looking at that whatif output I see that it's trying to pull an image `{local serverdir}\My Documents\WindowsPowerShell\Modules\BurntToast\0.6.3\Images\BurntToast.png`

On my system that "{local serverdir}" was the culprit, as it means that it's not referencing a valid path to an image. (Note, when I say valid I mean validly constructed... the image doesn't actually need to exist.)

Are you specifying an app override logo when running `New-BurntToastNotification`? If not, please double check your `config.json` file for an "AppLogo" setting. The [default](https://github.com/Windos/BurntToast/blob/master/BurntToast/config.json) is set to `"AppLogo":  "\\Images\\BurntToast.png"`

**Comment by Tuxhedoh** [comment]
Where is the config.json located?

**Comment by Tuxhedoh** [comment]
My config.json file has this - `
{
    "AppId":  "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\WindowsPowerShell\\v1.0\\powershell.exe",
    "AppLogo":  "\\Images\\BurntToast.png"
}
`

In our environment our My Docs are redirected to the server so that's where that ```{local serverdir}``` is a valid path. I've verified that the image exists in that location.  I'm definitely not specifying an override.

**Comment by Windos** [comment]
Hey @Tuxhedoh was the `{local serverdir}` naturally included in the output or was it put in there to protect the name of the server? Like was there a originally a UNC path there?

If there is normally a UNC path there, then I'm thinking you're running into the same issue as #56 

If that **is** how the path is naturally coming through... I'm not sure what I can do to work around it without installing the module in a different path*. Windows (or at least this specific API) is taking it and it's causing the XML to be invalid.

*If you were to install it to the local machine scope rather than user scope, I imagine it would run as expected as the path would end up being `C:\Program Files\...`.
