### ISSUE TITLE
Custom Text

### ISSUE THREAD

**Issue by jwood79** [Windos/BurntToast#63]
Not sure if this is an issue or not. When I run the script, is there a way to get rid of the text that says Windows PowerShell at all?

![burnttoast](https://user-images.githubusercontent.com/48693373/54562413-54a05e80-499d-11e9-83ef-f1218adcee6a.JPG)

**Comment by Windos** [comment]
Hey @jwood79, this is a bit of deep vortex of a topic.

In short, that text comes from the "AppID" or Application User Model ID, through which the toast is displayed.

The only way to completely remove it, is to remove the image on the left as well (though you then end up with an ugly small PowerShell logo) e.g.

```powershell
New-BurntToastNotification -AppLogo 'C:\fake.png` # Pointing at a non-existent image
```

![NoName](https://user-images.githubusercontent.com/6955786/54587629-868cf000-4a85-11e9-838b-703a0feadd4b.PNG)

The next question is, can it be changed? Yes, it **can**, but not freely or easily.

Check out the config.json file in the root of the module, you'll see a line in there for AppId. You can change this to anything that shows up when you run `Get-StartApps` (note, and slashes need to be doubled up, like the file contains by default, so that they are escaped properly).

You *can* create custom AppIds, but it's reasonably involved... I blogged about it [here](https://king.geek.nz/2018/03/03/burnttoast-wix/).

I'm hoping to find an easier way of doing this going forward... when I do it'll be the headline feature in a new release.
