### ISSUE TITLE
Question about notifications

### ISSUE THREAD

**Issue by jwood79** [Windos/BurntToast#64]
Quick question,

Is it possible to reuse a notification. We are trying to get people to reboot their computers more frequently after windows updates. I have a script that runs every 30 minutes and checks for a pending reboot, if there is one, a toast will be displayed. If a PC needs a reboot and the user is away  form their PC for say an hour, they will come back to multiple toast notifications. It would be nice to be able to reuse the same one over again if possible.

I was able to do this with the balloontip function, but not sure how to do this with the burnttoast function.

Thanks for an amazing script by the way. This has been very helpful.

**Comment by Windos** [comment]
Hey @jwood79, absolutely!

What you'll want to do is resend the notification and specify an ID with `-UniqueIdentifier` (this can be a string, numbers, whatever)

When Windows gets a Toast with the same unique identifier as a previous toast, it will "re-toast" (i.e. show the toast as if it were new) but also remove the old one. The ID needs to be on all the toasts (including the first) otherwise Windows won't know which toast to replace.

As an example:

```powershell
New-BurntToastNotification -Text 'Hey you, REBOOT!' -UniqueIdentifier 'RebootNag'
```

_(Full disclosure: "Unique Identifier" is my own term, behind the scenes this value is setting the "tag" and "group" on the toast... I'm just abstracting that away a little.)_
