### ISSUE TITLE
ExpirationTime CustomTimestamp 

### ISSUE THREAD

**Issue by cdric0701** [Windos/BurntToast#69]
I can not make these settings work. Which is the one that allows to leave the notification on screen for a long time? If yes, how ?
Thank you !

**Comment by Windos** [comment]
Hey @cdric0701, the short answer is neither.

ExpirationTime sets when the toast is no longer relevant and should be removed from the system (if it's still on the screen it'll dismiss itself and it'll also be removed from the Action Center.)

CustomTimestamp is for changing what the system displays as the time a toast was received. It's generally something you may use for a chat application where the message was received at, say, 11:50, but you know it'll take a minute or two to show the toast. Instead of letting Windows show the time the notification was received (11:52 ish) you set the time stamp to 11:50 in the code.

There's no "good" way to keep the toast displaying for a long time, unfortunately. It will display for longer if you choose a looping sounds, such as any of the call or alarm sounds.

If you're using the advanced functions (e.g. not `New-BurntToastNotification`) you can replicate a toast which displays for longer without having to play a specific sound. Specifically, look at both the `scenario`  (set this to alarm) and `duration` (set this to alarm) parameters on the `New-BTContent` function.
