### ISSUE TITLE
Application ID not customizable

### ISSUE THREAD

**Issue by pyonjohn** [Windos/BurntToast#96]
I use BurnToast for my personal PS script at home and I learnt that we could use a specific ApplicationID to display on the notification but it seems like it does not work anymore and I can't see any example describing that on your repo. Does something changed ?

**Comment by Windos** [comment]
Hey @puchijon, these AppIDs have been a thorn for a very long time.

The ability to use an arbitrary App ID was actually unknowingly exploiting a bug which was patched back in 2017 with the Fall Creators Update. This was raised in #20 and [blogged](https://toastit.dev/2017/10/08/burnttoast-no-appid/) about.

It *is* possible to use your own App ID, but it's a bit of a rigmarole. I've got two posts on this:

* [BurntToast + AppId = It's Working!](https://toastit.dev/2018/02/04/burnttoast-appid-installer/)
* [DIY AppId and WiX, for Tasty Toast](https://toastit.dev/2018/03/03/burnttoast-wix/)

There's an easier was now, rather than using WiX. It involves using [UD-Forge](https://github.com/ironmansoftware/ud-forge) from @adamdriscoll as the Forge installers creates the required start menu item with embedded App ID. Blogging about this has been on my to do list for a while now.

**Comment by Cenwulf** [comment]
Is it possible to add the custom app to the focus assist priority list and would doing this making burnt toast notifications obey the focus assist rules?

**Comment by pyonjohn** [comment]
> Hey @puchijon, these AppIDs have been a thorn for a very long time.
> 
> The ability to use an arbitrary App ID was actually unknowingly exploiting a bug which was patched back in 2017 with the Fall Creators Update. This was raised in #20 and [blogged](https://toastit.dev/2017/10/08/burnttoast-no-appid/) about.
> 
> It _is_ possible to use your own App ID, but it's a bit of a rigmarole. I've got two posts on this:
> 
> * [BurntToast + AppId = It's Working!](https://toastit.dev/2018/02/04/burnttoast-appid-installer/)
> * [DIY AppId and WiX, for Tasty Toast](https://toastit.dev/2018/03/03/burnttoast-wix/)
> 
> There's an easier was now, rather than using WiX. It involves using [UD-Forge](https://github.com/ironmansoftware/ud-forge) from @adamdriscoll as the Forge installers creates the required start menu item with embedded App ID. Blogging about this has been on my to do list for a while now.

Thanks a lot for your help ! Great job and keep going ! :)

**Comment by NebularNerd** [comment]
For those visiting in 2024 the links by @Windos above have changed to:

[BurntToast + AppId = It's Working!](https://toastit.dev/2018/02/03/burnttoast-appid-installer/)
[DIY AppId and WiX, for Tasty Toast](https://toastit.dev/2018/03/02/burnttoast-wix/)
